<a href="https://colab.research.google.com/github/fereshtehdehkhoda/Example14-Mean-of-array/blob/main/Mean_of_array.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Mean of array

In [ ]:
#یک ماتریس با 5 ردیف و 6 ستون بسازید که اعداد بین 1 تا 3 با فاصله یکنواخت از هم به صورت ستونی آن را پر کرده‌اند.
#میانگین درایه‌های ستون آخر کدام است؟

In [ ]:
import numpy as np

In [ ]:
c=np.linspace(1,3,30)
c

array([1.        , 1.06896552, 1.13793103, 1.20689655, 1.27586207,
       1.34482759, 1.4137931 , 1.48275862, 1.55172414, 1.62068966,
       1.68965517, 1.75862069, 1.82758621, 1.89655172, 1.96551724,
       2.03448276, 2.10344828, 2.17241379, 2.24137931, 2.31034483,
       2.37931034, 2.44827586, 2.51724138, 2.5862069 , 2.65517241,
       2.72413793, 2.79310345, 2.86206897, 2.93103448, 3.        ])

In [ ]:
c_T=c.reshape(5,6).T
c_T

array([[1.        , 1.4137931 , 1.82758621, 2.24137931, 2.65517241],
       [1.06896552, 1.48275862, 1.89655172, 2.31034483, 2.72413793],
       [1.13793103, 1.55172414, 1.96551724, 2.37931034, 2.79310345],
       [1.20689655, 1.62068966, 2.03448276, 2.44827586, 2.86206897],
       [1.27586207, 1.68965517, 2.10344828, 2.51724138, 2.93103448],
       [1.34482759, 1.75862069, 2.17241379, 2.5862069 , 3.        ]])

In [ ]:
last_column=c_T[:,-1]
last_column

array([2.65517241, 2.72413793, 2.79310345, 2.86206897, 2.93103448,
       3.        ])

In [ ]:
np.mean(last_column)

2.8275862068965516